### ISSUE TITLE
Wrong routing rule created on Android

### ISSUE THREAD

**Issue by yqs112358** [SagerNet/sing-tun#35]
Code at:
https://github.com/SagerNet/sing-tun/blob/f43daca5b7e6d3680dd4e32f557ebfe73819ddae/tun_linux.go#L575-L588

But when other Android VPN is enabled, `from all fwmark 0x0/0x20000 goto 9010` is created instead of the correct `0x20000/0x20000`

<img src="https://github.com/user-attachments/assets/3c5b8fc4-0bad-4b20-b924-83d9b547e714" width="50%" />

OverrideAndroidVPN has been set to `true` when calling `tun.NewDefaultInterfaceMonitor`.

**Comment by nekohasekai** [comment]
Thanks for your contribution. Please rebase and change the target branch to main, then we can continue.
