### ISSUE TITLE
question: How do the auto-route generated routing rules work?

### ISSUE THREAD

**Issue by j178** [SagerNet/sing-tun#6]
Hi SagerNet,

I'm a user of the [clash.meta](https://github.com/MetaCubeX/Clash.Meta) project, which depends on your sing-tun project. I'm having some trouble understanding how the auto-route feature works in my configuration. Could you please explain the purpose of the generated routing rules, specifically the rules in the `1970566510` table?

Here's an example of my configuration file:
```yaml
tun:
  enable: true
  stack: gvisor
  dns-hijack:
    - any:53
  auto-route: true
  auto-detect-interface: true
```

And here's an example of the generated routing rules:
```
jo@amd-desktop:~$ ip rule
0:      from all lookup local
9000:   from all to 198.18.0.0/30 lookup 2022
9001:   from all ipproto icmp goto 9010
9002:   not from all dport 53 lookup main suppress_prefixlength 0
9002:   not from all iif lo lookup 2022
9002:   from 0.0.0.0 iif lo lookup 2022
9002:   from 198.18.0.0/30 iif lo lookup 2022
9010:   from all nop
32766:  from all lookup main
32767:  from all lookup default
jo@amd-desktop:$ ip route show table 2022
default dev Meta
```

Any insights you could provide would be greatly appreciated. Thanks in advance for your help!

**Comment by novice88** [comment]
I have the same question, do you know how it works？

**Comment by sh0w1ov3** [comment]
为这个Linux下的tun路由混乱问题折腾了三五天，如果你也有这方面问题可以尝试下我那个#1774的处理方式

**Comment by us254** [comment]
- Rule 9000: Routes traffic to the 198.18.0.0/30 network (likely used for DNS) through table 2022.
   
   - Rule 9001: Directs ICMP traffic to rule 9010.
   
   - Rule 9002: Has several sub-rules:
     - Prevents DNS traffic (port 53) from using the main routing table.
     - Routes traffic not originating from the loopback interface through table 2022.
     - Routes traffic from 0.0.0.0 or 198.18.0.0/30 originating from the loopback interface through table 2022.

   - Rule 9010: No operation rule, likely used as a target for other rules.
———————-
In table 2022, there's a default route that sends all traffic to the TUN interface (named "Meta" in your case).

The purpose of these rules is to ensure that:

1. DNS traffic is properly handled and potentially intercepted by the TUN interface.
2. Regular internet traffic is routed through the TUN interface.
3. Certain local or special-use traffic is handled appropriately.
