### ISSUE TITLE
s.handler.NewConnection missing context

### ISSUE THREAD

**Issue by arm64v8a** [SagerNet/sing-tun#7]
https://github.com/SagerNet/sing-tun/blob/8507bb3a0a3da3511f02bb8f2bb100364d7c72c2/system.go#L197-L200

https://github.com/SagerNet/sing-tun/blob/8507bb3a0a3da3511f02bb8f2bb100364d7c72c2/gvisor.go#L139

**Comment by nekohasekai** [comment]
https://github.com/SagerNet/sing-tun/commit/20226b91c9b77147d28d836c80579e82cab115ce
